### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined method mysqli_stmt::get_result()

### ISSUE THREAD

**Issue by marcosmaia** [foraern/ethos-panel#1]
Fatal error: Uncaught Error: Call to undefined method mysqli_stmt::get_result() 
#1 {main} thrown in C:\MAMP\htdocs\lib\functions.php on line 103
not working

**Comment by ricardo-nolan** [comment]
Make sure you have mysqli extension enabled for your lamp stack.

I'm not familiar with MAMP, but should be something like:
extension=php_mysqli_mysqlnd.dll in php.ini

**Comment by marcosmaia** [comment]
php 7 cpanel not active  extension=php_mysqli_mysqlnd.dll

**Comment by marcosmaia** [comment]
With PDO this is much easier. They are asking to migrate, it's worth it

**Comment by ricardo-nolan** [comment]
If more users request it, I'll consider it, but no plans at present to switch to PDO.

**Comment by marcosmaia** [comment]
yes and because there are many shared hosting that no longer use this extension for example my
