### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by danielbowne** [foraern/ethos-panel#11]
Hey.  Tried running this project on my centos server and was getting HTTP ERROR 500.  So I spun up a new digital ocean droplet with Ubuntu and getting same issue.  Followed guide exactly.  Install.php works fine.  But after first login it creates a user in mysql, but then errors out.  Any suggestions?

**Comment by danielbowne** [comment]
`[Sun Jun 10 23:24:15.362371 2018] [:error] [pid 2648] [client 104.13.33.251:65052] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'miner_hashes' in 'field list' in /var/www/html/lib/functions.php:221\nStack trace:\n#0 /var/www/html/lib/functions.php(221): PDOStatement->execute()\n#1 /var/www/html/main.php(35): functions->getuserstats()\n#2 {main}\n  thrown in /var/www/html/lib/functions.php on line 221
[Sun Jun 10 23:29:04.672573 2018] [:error] [pid 1664] [client 212.83.214.18:1225] PHP Notice:  Undefined index: uid in /var/www/html/main.php on line 34
[Sun Jun 10 23:29:04.672920 2018] [:error] [pid 1664] [client 212.83.214.18:1225] PHP Notice:  Undefined index: uid in /var/www/html/lib/functions.php on line 210
[Sun Jun 10 23:29:04.673061 2018] [:error] [pid 1664] [client 212.83.214.18:1225] PHP Notice:  Trying to get property of non-object in /var/www/html/lib/functions.php on line 274
[Sun Jun 10 23:29:04.673323 2018] [:error] [pid 1664] [client 212.83.214.18:1225] PHP Notice:  Undefined variable: rigs in /var/www/html/lib/functions.php on line 284
[Sun Jun 10 23:29:04.673339 2018] [:error] [pid 1664] [client 212.83.214.18:1225] PHP Warning:  implode(): Invalid arguments passed in /var/www/html/lib/functions.php on line 284
[Sun Jun 10 23:29:04.673347 2018] [:error] [pid 1664] [client 212.83.214.18:1225] PHP Notice:  Trying to get property of non-object in /var/www/html/lib/functions.php on line 290
[Sun Jun 10 23:29:04.673710 2018] [:error] [pid 1664] [client 212.83.214.18:1225] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'miner_hashes' in 'field list' in /var/www/html/lib/functions.php:221\nStack trace:\n#0 /var/www/html/lib/functions.php(221): PDOStatement->execute()\n#1 /var/www/html/main.php(35): functions->getuserstats()\n#2 {main}\n  thrown in /var/www/html/lib/functions.php on line 221
[Sun Jun 10 23:30:19.402490 2018] [:error] [pid 1662] [client 104.13.33.251:65375] PHP Notice:  Undefined variable: rigs in /var/www/html/lib/functions.php on line 284
[Sun Jun 10 23:30:19.402531 2018] [:error] [pid 1662] [client 104.13.33.251:65375] PHP Warning:  implode(): Invalid arguments passed in /var/www/html/lib/functions.php on line 284
[Sun Jun 10 23:30:19.402885 2018] [:error] [pid 1662] [client 104.13.33.251:65375] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'miner_hashes' in 'field list' in /var/www/html/lib/functions.php:221\nStack trace:\n#0 /var/www/html/lib/functions.php(221): PDOStatement->execute()\n#1 /var/www/html/main.php(35): functions->getuserstats()\n#2 {main}\n  thrown in /var/www/html/lib/functions.php on line 221
[Sun Jun 10 23:30:22.418033 2018] [:error] [pid 1664] [client 104.13.33.251:65377] PHP Notice:  Undefined variable: rigs in /var/www/html/lib/functions.php on line 284
[Sun Jun 10 23:30:22.418057 2018] [:error] [pid 1664] [client 104.13.33.251:65377] PHP Warning:  implode(): Invalid arguments passed in /var/www/html/lib/functions.php on line 284
[Sun Jun 10 23:30:22.418426 2018] [:error] [pid 1664] [client 104.13.33.251:65377] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'miner_hashes' in 'field list' in /var/www/html/lib/functions.php:221\nStack trace:\n#0 /var/www/html/lib/functions.php(221): PDOStatement->execute()\n#1 /var/www/html/main.php(35): functions->getuserstats()\n#2 {main}\n  thrown in /var/www/html/lib/functions.php on line 221`

**Comment by danielbowne** [comment]
`PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'miner_hashes' in 'field list' in /var/www/html/lib/functions.php:221\nStack trace:\n#0 /var/www/html/lib/functions.php(221): PDOStatement->execute()\n#1 /var/www/html/main.php(35): functions->getuserstats()\n#2 {main}\n  thrown in /var/www/html/lib/functions.php on line 221
PHP Notice:  Undefined variable: rigs in /var/www/html/lib/functions.php on line 284
PHP Warning:  implode(): Invalid arguments passed in /var/www/html/lib/functions.php on line 284
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'miner_hashes' in 'field list' in /var/www/html/lib/functions.php:221\nStack trace:\n#0 /var/www/html/lib/functions.php(221): PDOStatement->execute()\n#1 /var/www/html/main.php(35): functions->getuserstats()\n#2 {main}\n  thrown in /var/www/html/lib/functions.php on line 221
PHP Notice:  Undefined variable: rigs in /var/www/html/lib/functions.php on line 284
PHP Warning:  implode(): Invalid arguments passed in /var/www/html/lib/functions.php on line 284
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'miner_hashes' in 'field list' in /var/www/html/lib/functions.php:221\nStack trace:\n#0 /var/www/html/lib/functions.php(221): PDOStatement->execute()\n#1 /var/www/html/main.php(35): functions->getuserstats()\n#2 {main}\n  thrown in /var/www/html/lib/functions.php on line 221`

**Comment by ricardo-nolan** [comment]
My apologies, I haven't updated the sql dump since the latest feature. I'll update it now.

**Comment by ricardo-nolan** [comment]
That should be up to date now, just do a git pull and either import ethos-panel.sql or re-install and it should work fine.

**Comment by danielbowne** [comment]
OK, that worked.  Noticing another bug.  When saving settings in profile.  They do not save.  Had to manually set dataorigin to 1 and emailnotifications to 1 to save the settings.  I manually ran the curl command and not seeing any data.

**Comment by danielbowne** [comment]
The error when CURL Runs: 
`[Mon Jun 11 10:45:43.408804 2018] [:error] [pid 14590] [client 104.13.33.251:62657] PHP Notice:  Undefined variable: rigs in /var/www/html/lib/functions.php on line 284, referer: http://ethos-panel.homebrewadmin.com/main.php
[Mon Jun 11 10:45:43.408855 2018] [:error] [pid 14590] [client 104.13.33.251:62657] PHP Warning:  implode(): Invalid arguments passed in /var/www/html/lib/functions.php on line 284, referer: http://ethos-panel.homebrewadmin.com/main.php
[Mon Jun 11 10:45:43.439463 2018] [:error] [pid 14590] [client 104.13.33.251:62657] PHP Notice:  Undefined property: stdClass::$coinwarz_api in /var/www/html/lib/calc.php on line 73, referer: http://ethos-panel.homebrewadmin.com/main.php
[Mon Jun 11 10:45:43.514676 2018] [:error] [pid 14590] [client 104.13.33.251:62657] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/lib/calc.php on line 77, referer: http://ethos-panel.homebrewadmin.com/main.php
[Mon Jun 11 10:45:43.514718 2018] [:error] [pid 14590] [client 104.13.33.251:62657] PHP Notice:  Undefined variable: blockinfo in /var/www/html/lib/calc.php on line 86, referer: http://ethos-panel.homebrewadmin.com/main.php
[Mon Jun 11 10:45:43.514726 2018] [:error] [pid 14590] [client 104.13.33.251:62657] PHP Notice:  Trying to get property of non-object in /var/www/html/lib/calc.php on line 109, referer: http://ethos-panel.homebrewadmin.com/main.php
[Mon Jun 11 10:45:43.514732 2018] [:error] [pid 14590] [client 104.13.33.251:62657] PHP Notice:  Trying to get property of non-object in /var/www/html/lib/calc.php on line 109, referer: http://ethos-panel.homebrewadmin.com/main.php
[Mon Jun 11 10:45:43.514737 2018] [:error] [pid 14590] [client 104.13.33.251:62657] PHP Warning:  Division by zero in /var/www/html/lib/calc.php on line 109, referer: http://ethos-panel.homebrewadmin.com/main.php`

**Comment by ricardo-nolan** [comment]
I'll have a look in a bit, most of the testing was done via local or live site, so didn't have an empty db, I'll have a look with a fresh install to see what's happening.

**Comment by danielbowne** [comment]
@foraern Hey, I am an idiot.  I was sending info to your server.  I forgot the URL generated is for your server.  Fixed and working.

**Comment by ricardo-nolan** [comment]
No worries, I'll close this now.
