### ISSUE TITLE
Dashboard Hashrate Chart not working properly when using "Direct from Rig" option.

### ISSUE THREAD

**Issue by danielbowne** [foraern/ethos-panel#12]
When using direct from rig option, Dashboard graph shows "Please provide your ethos url in your profile" and does not display hashrate graph.  

Screenshot:
https://prnt.sc/jtn3ph

@foraern Please let me know if you want me to keep posting bugs or to leave you alone :)  This tool is bad ass!  Keep up the great work.

**Comment by danielbowne** [comment]
I commented out the following on main.php as a temp fix.  Need some kind of logic that looks at "Direct from Rig" method.
` /*
if(empty($f->user->url)){
	$contentdata["urlwarning"]="<h4>Please provide your ethos url in your <a href='./profile.php'>profile</a></h4>";
}
else{
	$contentdata["urlwarning"]="";
}
 */
`

**Comment by ricardo-nolan** [comment]
>@foraern Please let me know if you want me to keep posting bugs or to leave you alone :) This tool is bad ass! Keep up the great work.

Keep them coming :) Since I'm the sole dev, I don't exactly have time for full QA, so bugs are inevitable, and if people don't let me know about them, they tend to stick around until I happen to come across them.

Regarding the issue itself, I'll add in the logic later today.

**Comment by ricardo-nolan** [comment]
committed fix for this.
