### ISSUE TITLE
GPU Count on Dashboard

### ISSUE THREAD

**Issue by danielbowne** [foraern/ethos-panel#13]
Using Rig GPU Method. GPU count is not accurate.  Hashrate is 0 and memstate is 0 on gpu 0.  Dashboard shows 6/6 GPU.  Should be 5/6 similar to ethos panel?

https://prnt.sc/jtnffg

**Comment by ricardo-nolan** [comment]
Good catch, I'll fix that later today.

**Comment by ricardo-nolan** [comment]
I've just committed the fix for this in post.php
