### ISSUE TITLE
Data Origin ethosdistro.com

### ISSUE THREAD

**Issue by Cryptaco** [foraern/ethos-panel#16]
Hi, really good job, I have a problem both using your panel and installing on my server. When I try to insert a new link in ethosdistro.com "URL" in User Profilo, after saving the changes are not made. How can I solve? Thanks!

**Comment by ricardo-nolan** [comment]
I'll look into it...looks like a bug

**Comment by trungthanh1288** [comment]
i have same problems

**Comment by Cryptaco** [comment]
Hi, I partially solved the problem, the ethos API are blocked. So you have to install the script directly rig by rig.

**Comment by ricardo-nolan** [comment]
I'm not sure what you mean by the ethos API being blocked...can you clarify?
Or do you mean that this is an unpaid version of ethos and they've blocked the dashboard?

**Comment by ricardo-nolan** [comment]
Sorry for the delay guys, as mentioned, there was a bug that prevented the profile page from saving the ethosdistro.com url.

That has now been fixed.
