### ISSUE TITLE
Web Server connection failed

### ISSUE THREAD

**Issue by jianyi85** [foraern/ethos-panel#17]
Hi foraern,

Good day, I just want to report that we cannot access to your webserver at this moment, it show the error message below access to https://ethos-panel.com/

Connection failed: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)

Regards,
Alex Wong

**Comment by ricardo-nolan** [comment]
Thanks, I’ll look into it tonight

**Comment by ricardo-nolan** [comment]
That's sorted.
