### ISSUE TITLE
remote conf URL

### ISSUE THREAD

**Issue by QQ40451** [foraern/ethos-panel#18]
When accesss  the conf url ,report 'Not Found
The requested URL /remote/fa1b54b1d57cfa51833e was not found on this server.';

**Comment by ricardo-nolan** [comment]
Can you clarify?

This one seems to work fine: https://ethos-panel.com/remote/dc34ad0d74a66d651a42

Did you save your config?

**Comment by ricardo-nolan** [comment]
Checked the db and I can't find your remote config: fa1b54b1d57cfa51833e, so as far as I can tell, it wasn't saved...

**Comment by QQ40451** [comment]
I build  one  myself.   After save ，The conf is right  in mysql；  but  URL  cant  access。  by the way,  I  have  chaneg  https  to  http...

**Comment by ricardo-nolan** [comment]
That will depend a lot on your own server and domain setup...are you using a domain, or is it running on a private network?

Can you provide more details?

**Comment by QQ40451** [comment]
on a domain.  panel.40451.net    ,It  works well  except remote conf cant  access;

**Comment by ricardo-nolan** [comment]
registered on your domain.

2 problems with remoteconf on your site is that you're not using SSL and/or you're not using htaccess.

Enable htaccess on your webserver (apache?).

Change line 57 on remoteconf.php on your site to use http instead of https and it should work.

**Comment by QQ40451** [comment]
Thanks  for  reply, it‘’s done;

just modify  apache2.conf    change  "Options FollowSymLinks
AllowOverride None“ TO 
”Options FollowSymLinks
AllowOverride All"
Methord for others.
