### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by up2uguys** [foraern/ethos-panel#19]
Hi,
How to add condition rig on table like ethosdistro panel, (mining, unreacheble, Thortle, stuck miner, etc) please help to add condition on stats.json, thank you

**Comment by up2uguys** [comment]
How to get condition of Rig without api of ethosdistro.com/?json=yes,  (direct from rig), "condition" not on list of stats.json, thanks for help foraern

**Comment by ricardo-nolan** [comment]
At the moment, there's no concept of "condition", I'd need to build in logic for it.
As with other feature requests, I won't be doing any major work until winter.

**Comment by up2uguys** [comment]
ok thank you Foraern. what about the total GPU ..? I see there is a feature of all hasrates on the panel, can the total feature of all gpu be displayed? how is the code? For example: Total all GPU is : 500/500, so one VGA error becomes 499/500, like total gpu per rig,  so it will be more quickly known if there is a VGA error in one farm, Thank for help

**Comment by ricardo-nolan** [comment]
yes and no. 
the basis for getting the GPUS is the following from ethos:
"gpus": 6,
"miner_hashes": "27.92 27.98 27.98 27.99 27.99 28.01",

So we can tell if a gpu is failing, but we can't tell if the status. So basically it's an on/off switch, the gpu is either working or it's not.

I have similar logic in https://github.com/foraern/ethos-panel/blob/master/utilities/rigcheck.php
