### ISSUE TITLE
Cant create user/login

### ISSUE THREAD

**Issue by DamianMachola** [foraern/ethos-panel#3]
I get this error
Fatal error: Uncaught Error: Call to undefined method mysqli_stmt::get_result() in /home/currpuhm/public_html/lab/lib/functions.php:103 Stack trace: #0 /home/currpuhm/public_html/lab/index.php(35): functions->login('damianmachola@g...', 'Password') #1 {main} thrown in /home/currpuhm/public_html/lab/lib/functions.php on line 103

**Comment by ricardo-nolan** [comment]
Hi, you need to enable mysqli on your server.

Try: 
apt-get install php-mysqlnd
or one of the other options in the link below:
https://stackoverflow.com/questions/7250356/how-to-install-mysqli

**Comment by marcosmaia** [comment]
execute phpinf (); and see if mysqlnd is active.
which hosting you this? and shared?

**Comment by DamianMachola** [comment]
it is active, shared hosting.

**Comment by ricardo-nolan** [comment]
Try this:

php 7:

sudo apt-get install php7.0-mysqli
php 5:

sudo apt-get install php5-mysqli

**Comment by marcosmaia** [comment]
mysqlnd is also active? see has this as in the image below
![img](https://user-images.githubusercontent.com/13109793/36387372-8d03e07c-1577-11e8-9b18-1eb78ab1265c.jpg)
localhost is working
mine is also shared and did not work due to mysqlnd
ask for it changes to PDO. more so if other users request most of the shared hosting does not have mysqlnd compiled

**Comment by ricardo-nolan** [comment]
I'll start converting to PDO today or tomorrow...should be simple enough since it's all in prepared statements already, the major change is in the connection.

**Comment by marcosmaia** [comment]
@foraern 
Try this:

php 7:

sudo apt-get install php7.0-mysqli
php 5:

sudo apt-get install php5-mysqli

Extensions

**Comment by DamianMachola** [comment]
https://www.screencast.com/t/bDvaoo0maQ

**Comment by DamianMachola** [comment]
is this correct? they seemed to fix it however they broke my main domain

**Comment by ricardo-nolan** [comment]
@DamianMachola I think you have something else going on there...none of the styles are loading...

**Comment by marcosmaia** [comment]
@DamianMachola 
copy assets to root of public_thml

**Comment by ricardo-nolan** [comment]
this is what it should look like:

https://imgur.com/a/NVgCh

https://imgur.com/a/Bl4xN

**Comment by marcosmaia** [comment]
@DamianMachola 
Redirect your domain to / lab or install at the root or try copy assets to root of public_thml

**Comment by DamianMachola** [comment]
@marcosmaia 
I just moved assets to default dir and it works like a charm. What would I need to need to edit to change the default dir in the script, since its redirecting me to main site when i press dashboard and log out

**Comment by ricardo-nolan** [comment]
you need to change the html templates, they all have links to "/", and the same in the main php files (in root directory), anywhere you see header('location: /') to point to the folder you use.

May be easier just to create a new virtualhost and point it to the folder and use the folder as the root folder for that virtualhost.
